service: backoffice-app-total

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

resources:
  - ${file(resources/api-gateway-errors.yml)}

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1

  environment:
    tableName: columnist
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb: DescribeTable
  #       - dynamodb: Query
  #       - dynamodb: Scan
  #       - dynamodb: GetItem
  #       - dynamodb: PutItem
  #       - dynamodb: UpdateItem
  #       - dynamodb: DeleteItem
  #     Resource: "arn:aws:dynamodb:us-east-1:754156944485:table/columnist"

functions:
  create:
    handler: create.main
    events:
      - http:
          path: columnist
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: get.main
    events:
      - http:
          path: columnist/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: list.main
    events:
      - http:
          path: columnist
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: update.main
    events:
      - http:
          path: columnist/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: delete.main
    events:
      - http:
          path: columnist/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  billing:
    handler: billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
